### ISSUE TITLE
Weighing fractions by cell size

### ISSUE THREAD

**Issue by jasonserviss** [EngeLab/CIMseq#48]
Fractions may more accurately reflect the expected fractions if they are weighted by cell size. A doublet with cell type A and B is expected to have fractions 0.5 and 0.5 but if cell type a is 50% smaller than cell type B the fractions will instead be 0.25 and 0.75. Not sure if this is really useful to do but could help in evaluating which fractions are valid and which are background.

**Comment by EngeLab** [comment]
This bug is for an obsolete version, fixed in current.
